### ISSUE TITLE
A bit confused, would be grateful for two answers

### ISSUE THREAD

**Issue by MatthaisUK** [ovesco/scribio#7]
Hi.  Appreciate this repo hasn't seen much use since you made it a year, but it's exactly what I need as a native solution to replace the outdated jQuery x-editable. However, I'm a bit confused on a couple of counts which I'd be very grateful if you could clarify for me:

1) There is no "scribio.min.js", "scribio.bootstrap-theme.min.js" or "scribio.popper.min.js" in the root directory.  Instead there's "/src/Scribio.js", with the Bootstrap Theme at "/src/build/build.bootstrap-theme.js".  Is this correct?
2) I'm already including popper.js with Bootstrap 4 (both via CDN) on all my pages, while I'll just be using Scribio on a single page (but for a significant number of inputs).  How's it best to handle popper.js for Scribio in this case?

**Comment by ovesco** [comment]
Hey Thanks for your interest in this project ! As you pointed out i havent been working on it for the past year but I'm currently rewriting it in Typescript for another project. If you can wait till the end of the week I should publish it this week-end, the API wont change much but it's more stable and many bugs are being corrected with it.

To answer your questions (which Will also be valid for the next iteration)
- I didnt publish the minified file on github but it can be easily generated, it Will be present with next iteration
- If popper is available everywhere on page then you dont need to do anything, just include scribio after it so that it can find it through `window.Popper`

**Comment by MatthaisUK** [comment]
Thanks for your reply; happy to hear you're still working on the project.

1)  Not something I've done before; I'd just maybe mention that in your documentation.  Linking to files which aren't automatically included just leaves a bit of room for confusion IMO.
2)  Great, I was hoping it was that simple, but didn't want to assume.

As I wasn't sure whether I'd hear from you I've been working on my own solution using _contenteditable_, but I'll certainly be keeping an eye out for your rewrite in case my attempts aren't successful.

Thanks again for your time and good luck.

**Comment by ovesco** [comment]
Hey, I released the lib I used in my project (and made it usable easily), it's based on the same principles as Scribio but more extendable and configurable, shipping with an inline renderer too.

https://ovesco.github.io/flyter/

**Comment by MatthaisUK** [comment]
Thanks for letting me know, I'll check it out.
